Hello-world project
Isabellanamutenda/Hello-microverse pull request #1
Opened 2021-07-06 15:28 UTC by Isabellanamutenda

2021-07-06 15:42 UTC, abruzy requested changes
Hi @Isabellanamutenda   👏 , 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Required Changes! ♻️ 
_1. Kindly check the comments under the review._
_2. Let's make your repo looks professional by applying one of the  5 professional repo basic rules, kindly update your `README` file.
Checkout out the below link for help, feel free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright_
_3. delete the gitignore.md file you created, you create ```.gitignore``` and add test.md and node_modules inside the file.
_4. fix the linting errors as well

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 15:42 UTC, abruzy commented on README.md
> +![screenshot](./app_screenshot.png)
Good job 👍🏽 

kindly fix the screenshot to show in the preview

2021-07-06 15:42 UTC, abruzy commented on README.md
> +      -set up the linters of html and css
Good job 👍🏽 
this is not proper way to setup the app on the person machine. You want to follow this step instead

- [ ] clone the repo
- [ ] install dependencies

And so on

kindly fix that

2021-07-06 21:20 UTC, Isabellanamutenda commented on README.md
> +![screenshot](./app_screenshot.png)
Resolved

2021-07-06 21:31 UTC, Isabellanamutenda commented on README.md
> +      -set up the linters of html and css
Resolved

2021-07-06 21:56 UTC, voscarmv requested changes
Hi @Isabellanamutenda , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Please add a proper Pull Request description. This description may contain a summary of the concepts you learned in completing this project. Currently, your PR description is empty, please fix this! 
 ![image](https://user-images.githubusercontent.com/2739245/124670328-71684500-de79-11eb-983a-9b6726c0e046.png)
- [ ] Your linters are still throwing errors in this PR. Please fix your `style.css` file:
![image](https://user-images.githubusercontent.com/2739245/124670710-010df380-de7a-11eb-9ed7-6dfdaad83c77.png)
- [ ] Your `.gitignore` file requires some changes which were specified previously but were not carried out correctly.

_Check the comments under the review._

## Optional suggestions

- We may try to start implementing best HTML practice early. I've left one optional suggestion for this.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 21:56 UTC, voscarmv commented on gitignore.md
> +test.md should be ignored by git
- [ ] This file should be names `.gitignore`, *not* `gitignore.md`, please fix this.
- [ ] The content of this file should be:
```
test.md
node_modules
```

2021-07-06 21:56 UTC, voscarmv commented on index.html
> +</html>
- [ ] **[OPTIONAL]** You may use 2-space indentation in your HTML files in order to keep with best HTML practices.

2021-07-06 21:59 UTC, voscarmv reviewed
@Isabellanamutenda  here are some additional code comments I missed on my previous review. Cheers!
- [ ] These are the 4 linter errors still showing up in the Pull Request. Please fix them before submitting again!

2021-07-06 21:59 UTC, voscarmv commented on style.css
> +    }
- [ ] Your `style.css` file is showing the following linter mistakes. Please fix them:

![image](https://user-images.githubusercontent.com/2739245/124671665-70381780-de7b-11eb-9b7e-a2e910ea1626.png)

2021-07-06 22:53 UTC, Isabellanamutenda commented on gitignore.md
> +test.md should be ignored by git
I have a question  on the instructions we were told to name it .gitignore.md should I really change it.

2021-07-07 05:27 UTC, Isabellanamutenda commented on gitignore.md
> +test.md should be ignored by git
Resoolved

2021-07-07 06:25 UTC, Isabellanamutenda commented on style.css
> +    }
Resolved

2021-07-07 07:03 UTC, Emmyn5600 approved these changes
## STATUS: APPROVED :muscle::clap:

### Hi, @Isabellanamutenda 

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous code reviewers :clap:

### Highlights
   * #### You have the descriptive Readme:heavy_check_mark:
   * #### You have descriptive commits :heavy_check_mark:
   * ####  Your Linters are passing successful:heavy_check_mark:
   * #### You have a proper Pull Request description that contain a summary of the concepts you learned in completing this project. :heavy_check_mark:
   * #### Nice work to commit oftentimes :heavy_check_mark:
  

### Optional suggestions
  * #### N/a

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
    
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-07 07:10 UTC, merged